name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    container:
      image: ghcr.io/emqx/emqx-builder/5.0-14:1.13.3-24.2.1-1-ubuntu20.04

    steps:
    - uses: actions/checkout@v2
    - name: Xref
      run: make xref
    - name: Make release
      run: make rel
